### ISSUE TITLE
Sort bugs: Adding new internship application after sorting is not added in order

### ISSUE THREAD

**Issue by snowstopxt** [AY2425S1-CS2103T-W09-3/tp#148]
- when adding a new internship application after sorting by earliest, does not add it in order. May or may not be a bug?
<img width="950" alt="image" src="https://github.com/user-attachments/assets/00d47038-6a10-42ae-ac3a-f57cc8454983">

**Comment by choaticman** [comment]
Closed due to specificity of feature.
