### ISSUE TITLE
[PE-D][Tester B] Error message overflows from console

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W09-3/tp#240]
The error message for email validation overflows from the console box when the window is small, needing the user to scroll through to view the entire message. Perhaps some form of wrapping can be done to improve user experience?

![image.png](https://raw.githubusercontent.com/SherniceSng/ped/main/files/90d17269-7406-478b-91ec-f25341d841f1.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: SherniceSng/ped#1

**Comment by choaticman** [comment]
Not a bug
