### ISSUE TITLE
[PE-D][Tester D] Is this a valid email id? 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W09-3/tp#288]
Should an email contain more than one . in its domain? 

![Screenshot 2024-11-08 at 5.32.34 PM.png](https://raw.githubusercontent.com/triishaa/ped/main/files/767726d9-4bc0-4fb2-b779-dfa4aebca9a9.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: triishaa/ped#27

**Comment by ZweZeya** [comment]
> hould an email contain more than one . in its domain?

yes
