### ISSUE TITLE
[PE-D][Tester B] Improvement in wording for UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W09-3/tp#294]
![image.png](https://raw.githubusercontent.com/SherniceSng/ped/main/files/c7864f57-558c-4e82-8fae-db5bdd4ee83c.png)
- This line might come across as conflicting as if future dates cannot be used, the user will not be able to input a year beyond the present one, let along 2099. So perhaps the wording can be improved to help with readability?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: SherniceSng/ped#8

**Comment by choaticman** [comment]
Change `2099` to `the current year`
