### ISSUE TITLE
[PE-D][Tester A] Wrong find command format in diagram in DG 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W09-3/tp#308]
![image.png](https://raw.githubusercontent.com/Professional-Procrastinat0r/ped/main/files/e0fa5e6c-31c1-4bab-b9eb-549cf5011261.png)

Diagram shows `execute(/find" + keywords)`, when it should be `execute(/find " + keywords)`. Eg,
`/findGoogle` vs `/find Google`

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: Professional-Procrastinat0r/ped#14

**Comment by choaticman** [comment]
add a space
