### ISSUE TITLE
[PE-D][Tester A] Exit command sequence diagram omits interaction with Model in DG

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W09-3/tp#311]
![image.png](https://raw.githubusercontent.com/Professional-Procrastinat0r/ped/main/files/3aef1ff9-67aa-4e79-9987-86924850afab.png)

`/exit` creates data file, but sequence diagram in DG omitted interaction with Model and Storage.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Professional-Procrastinat0r/ped#17

**Comment by choaticman** [comment]
Can put a note in the diagram to state that Model is not used, but included for clarity sake as there is an `execute(m)`
